-- S004: Estimates FK Constraints
-- Date: 2026-07-13
-- Change: 添加 Estimates.BomVersionId → BomVersions(Id) 外键约束 (v2 L-7)
-- Status: SQLite 不支持 ALTER TABLE ADD CONSTRAINT。
--         外键完整性由应用层 Repository 保证。
--         V2.0 迁移至 PostgreSQL/SQL Server 时添加正式 FK 约束。
--
-- 注意: 此迁移不修改表结构。IX_Estimates_BomVersion 索引
--       已在 S001_InitialSchema.sql 中创建，此处无需重复。
